# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:17.2
    resource_class: small
    working_directory: ~/repo

jobs:
  do_nothing:
    executor: node

    steps:
      - run: print -- "Do nothing!"

workflows:
  version: 2

  build:
    jobs:
      - do_nothing:
          filters:
            branches:
              only:
                - only-execute-this-on-a-branch-that-will-hopefully-never-exist
