<template>
  <v-row wrap>
    <v-col cols="12" sm="4">
      <v-btn
        :disabled="working"
        variant="outlined"
        block
        color="primary"
        data-cy="import-empty"
        @click="importData(emptyProject)"
      >
        Empty
      </v-btn>
    </v-col>
    <v-col cols="12" sm="4">
      <v-menu :disabled="working" bottom>
        <template #activator="{ props: activatorProps }">
          <v-btn
            :disabled="working"
            variant="outlined"
            block
            color="primary"
            v-bind="activatorProps"
            >Examples</v-btn
          >
        </template>
        <v-list>
          <v-list-item
            v-for="(example, i) in examples"
            :key="'example' + i"
            @click.stop
          >
            <v-list-item-title @click="importExample(example.load)">{{
              example.title
            }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </v-col>
    <v-col cols="12" sm="4">
      <v-btn
        :disabled="working"
        variant="outlined"
        block
        color="primary"
        @click="openFileChooser"
      >
        File
      </v-btn>
    </v-col>

    <div style="height: 0px; width: 0px; overflow: hidden">
      <input
        ref="fileInput"
        :accept="importAccept"
        type="file"
        @input="retrieveFile"
        @change="retrieveFile"
      />
    </div>

    <v-dialog :model-value="isRevealed" max-width="600">
      <template #activator></template>

      <v-card title="Warning">
        <template #prepend>
          <v-icon color="warning" icon="mdi-alert"></v-icon>
        </template>
        <v-card-text>
          <p v-if="scriptImportWarning">
            Imported project won't contain node positions (nodes will be placed
            automatically when you open the canvas), labels and a few other
            things (they're not present in the script). Most data (like nodes,
            ports, links, hostnames, IPs, other settings…) will be imported just
            fine.
          </p>
          <p v-if="scriptImportWarning">
            This function is intended only for scripts generated by
            <strong>Mininet Editor</strong> or <strong>MiniEdit</strong>.
            Importing a custom script is possible but highly unreliable. Such
            project may be incomplete or dysfunctional.
          </p>

          <p>
            This will <strong>erase all your work</strong> (except what you have
            exported).
            <br />
            Are you sure you want to continue?
          </p>
        </v-card-text>

        <v-card-actions>
          <v-spacer />

          <v-btn
            text="Keep existing project"
            color="gray"
            data-cy="import-warning-cancel"
            @click="cancel"
          />
          <v-btn
            text="Import"
            color="warning"
            data-cy="import-warning-confirm"
            @click="confirm"
          />
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-row>
</template>

<script setup>
import { ref, computed } from "vue";
import { useConfirmDialog } from "@vueuse/core";
import importer from "@/importer";

import exampleEmpty from "@/examples/empty";
import { useTopologyStore } from "@/composables/useTopologyStore";

const {
  working: storeWorking,
  setWorking,
  setAlert,
  clearAlert,
  importData: storeImportData,
} = useTopologyStore();
const emit = defineEmits(["log"]);
const { isRevealed, reveal, confirm, cancel } = useConfirmDialog();

const fileInput = ref(null);
const scriptImportWarning = ref(false);

const emptyProject = exampleEmpty;
const examples = [
  {
    title: "Tiny without controller",
    load: () => import("@/examples/tiny.json"),
  },
  {
    title: "Tiny with controller",
    load: () => import("@/examples/tiny_controller.json"),
  },
  {
    title: "Tiny with physical interface",
    load: () => import("@/examples/tiny_physical_interface.json"),
  },
  {
    title: "Tiny with traffic control",
    load: () => import("@/examples/tiny_tc.json"),
  },
  {
    title: "Tiny with Mininet settings",
    load: () => import("@/examples/tiny_mininet_conf.json"),
  },
  {
    title: "Medium with 1 controller",
    load: () => import("@/examples/medium_1_controller.json"),
  },
  {
    title: "Medium with 2 controllers",
    load: () => import("@/examples/medium_2_controllers.json"),
  },
];

const working = computed({
  get() {
    return !!storeWorking.value;
  },
  set(value) {
    if (value) {
      clearAlert();
    }
    setWorking({ working: !!value });
  },
});

const importAccept = importer.importAccept;

function showAlert(type, text) {
  setAlert({ type, text });
}

function openFileChooser() {
  fileInput.value.click();
}

async function confirmImport(importData, warnings = []) {
  scriptImportWarning.value = warnings.includes("script-import-warning");

  const { isCanceled } = await reveal();

  if (isCanceled) {
    showAlert("info", "Import canceled.");
  } else {
    storeImportData(importData);
    showAlert("success", "Successfully imported.");
  }
}

function retrieveFile() {
  const input = fileInput.value;
  const file = input.files[0];
  input.value = "";

  // Some browsers emit input, some change and some both.
  // Return if the file was already collected by the other event handler.
  if (!file) {
    return;
  }

  working.value = true;

  const fr = new FileReader();
  fr.readAsBinaryString(file);
  fr.onloadend = async () => {
    try {
      const { data, log, warnings } = importer.stringToImport(
        file.type,
        file.name,
        fr.result,
      );
      emit("log", log);
      await confirmImport(data, warnings);
    } catch (error) {
      if (error instanceof TypeError) {
        showAlert("error", error.message);
      } else {
        console.error(error);
        showAlert("error", "Import failed.");
      }
    } finally {
      working.value = false;
    }
  };
}

async function importExample(load) {
  working.value = true;
  try {
    const mod = await load();
    await confirmImport(mod.default);
  } finally {
    working.value = false;
  }
}

async function importData(data) {
  working.value = true;
  await confirmImport(data);
  working.value = false;
}
</script>
