<template>
  <v-row wrap>
    <v-col cols="12" sm="4">
      <v-btn
        :disabled="working"
        variant="outlined"
        block
        color="primary"
        data-cy="import-empty"
        @click="importData(emptyProject)"
      >
        Empty
      </v-btn>
    </v-col>
    <v-col cols="12" sm="4">
      <v-menu :disabled="working" bottom>
        <template #activator="{ on }">
          <v-btn
            :disabled="working"
            variant="outlined"
            block
            color="primary"
            v-on="on"
            >Examples</v-btn
          >
        </template>
        <v-list>
          <v-list-item
            v-for="(example, i) in examples"
            :key="'example' + i"
            @click.stop
          >
            <v-list-item-title @click="importData(example.data)">{{
              example.title
            }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </v-col>
    <v-col cols="12" sm="4">
      <v-btn
        :disabled="working"
        variant="outlined"
        block
        color="primary"
        @click="openFileChooser"
      >
        File
      </v-btn>
    </v-col>

    <div style="height: 0px; width: 0px; overflow: hidden">
      <input
        ref="fileInput"
        :accept="importAccept"
        type="file"
        @input="retrieveFile"
        @change="retrieveFile"
      />
    </div>

    <v-dialog :model-value="isRevealed" max-width="600">
      <template #activator></template>

      <v-card title="Warning">
        <template #prepend>
          <v-icon color="warning" icon="mdi-alert"></v-icon>
        </template>
        <v-card-text>
          <p v-if="scriptImportWarning">
            Imported project won't contain node positions (nodes will be placed
            automatically when you open the canvas), labels and a few other
            things (they're not present in the script). Most data (like nodes,
            ports, links, hostnames, IPs, other settings…) will be imported just
            fine.
          </p>
          <p v-if="scriptImportWarning">
            This function is intended only for scripts generated by
            <strong>Mininet Editor</strong> or <strong>MiniEdit</strong>.
            Importing a custom script is possible but highly unreliable. Such
            project may be incomplete or dysfunctional.
          </p>

          <p>
            This will <strong>erase all your work</strong> (except what you have
            exported).
            <br />
            Are you sure you want to continue?
          </p>
        </v-card-text>

        <v-card-actions>
          <v-spacer />

          <v-btn
            text="Keep existing project"
            color="gray"
            data-cy="import-warning-cancel"
            @click="cancel"
          />
          <v-btn
            text="Import"
            color="warning"
            data-cy="import-warning-confirm"
            @click="confirm"
          />
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-row>
</template>

<script>
import importScript from "@/importScript";
import { ref } from "vue";
import { mapGetters } from "vuex";
import { useConfirmDialog } from "@vueuse/core";

import exampleEmpty from "@/examples/empty";
import exampleMedium1C from "@/examples/medium_1_controller";
import exampleMedium2C from "@/examples/medium_2_controllers";
import exampleTiny from "@/examples/tiny";
import exampleTinyController from "@/examples/tiny_controller";
import exampleTinyMininetConf from "@/examples/tiny_mininet_conf";
import exampleTinyPhysicalInterface from "@/examples/tiny_physical_interface";
import exampleTinyTC from "@/examples/tiny_tc";

export default {
  name: "ImportSection",
  setup: () => {
    const { isRevealed, reveal, confirm, cancel } = useConfirmDialog();

    return {
      isRevealed,
      reveal,
      confirm,
      cancel,

      scriptImportWarning: ref(false),
    };
  },
  data: () => ({
    emptyProject: exampleEmpty,
    examples: [
      {
        title: "Tiny without controller",
        data: exampleTiny,
      },
      {
        title: "Tiny with controller",
        data: exampleTinyController,
      },
      {
        title: "Tiny with physical interface",
        data: exampleTinyPhysicalInterface,
      },
      {
        title: "Tiny with traffic control",
        data: exampleTinyTC,
      },
      {
        title: "Tiny with Mininet settings",
        data: exampleTinyMininetConf,
      },
      {
        title: "Medium with 1 controller",
        data: exampleMedium1C,
      },
      {
        title: "Medium with 2 controllers",
        data: exampleMedium2C,
      },
    ],
  }),
  computed: {
    ...mapGetters("topology", ["data"]),
    working: {
      get() {
        return !!this.$store.state.working;
      },
      set(value) {
        if (value) {
          this.$store.commit("clearAlert");
        }
        this.$store.commit("setWorking", { working: !!value });
      },
    },
    importers() {
      function json(json) {
        return { data: JSON.parse(json), log: [] };
      }
      function python(script) {
        return importScript(script);
      }
      return {
        ".json": json,
        ".py": python,
        "application/json": json,
        "application/x-python-code": python,
        "text/x-python": python,
        json,
        python,
      };
    },
    importAccept() {
      return Object.keys(this.importers)
        .filter((key) => /(^.|\/)/.test(key))
        .join(",");
    },
  },
  methods: {
    showAlert(type, text) {
      this.$store.commit("setAlert", { type, text });
    },
    openFileChooser() {
      const input = this.$refs.fileInput;
      input.click();
    },
    retrieveFile() {
      const input = this.$refs.fileInput;
      const file = input.files[0];
      input.value = "";

      // Some browsers emit input, some change and some both.
      // Return if the file was already collected by the other event handler.
      if (!file) {
        return;
      }

      this.working = true;

      const fr = new FileReader();
      fr.readAsBinaryString(file);
      fr.onloadend = async () => {
        try {
          const stringToImport =
            this.importers[file.type] ||
            this.importers[file.name.replace(/^.*(?=\.)/, "")];
          if (stringToImport) {
            const str = fr.result;
            const { data, log } = stringToImport(str);
            this.$emit("log", log);
            if (stringToImport === this.importers.python) {
              await this.confirmImport(data, ["script-import-warning"]);
            } else {
              await this.confirmImport(data);
            }
          } else {
            this.showAlert("error", `Unknown file format: “${file.type}”.`);
          }
        } catch (error) {
          console.error(error);
          this.showAlert("error", "Import failed.");
        } finally {
          this.working = false;
        }
      };
    },
    async importData(data) {
      this.working = true;
      await this.confirmImport(data);
      this.working = false;
    },
    async confirmImport(importData, warnings = []) {
      this.scriptImportWarning = warnings.includes("script-import-warning");

      const { isCanceled } = await this.reveal();

      if (isCanceled) {
        this.showAlert("info", "Import canceled.");
      } else {
        this.$store.commit("topology/importData", importData);
        this.showAlert("success", "Successfully imported.");
      }
    },
  },
};
</script>
